on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Validate Makefile
    runs-on: ubuntu-latest
    steps:
      - name: Validate Makefile
        run: |
          cd holbertonschool-validation
          make help
